
export const WORD_LIST = [
    { word: "Airplane", category: "Transport" },
    { word: "Bicycle", category: "Transport" },
    { word: "Library", category: "Places" },
    { word: "Hospital", category: "Places" },
    { word: "Pizza", category: "Food" },
    { word: "Sushi", category: "Food" },
    { word: "Guitar", category: "Instruments" },
    { word: "Piano", category: "Instruments" },
    { word: "Elephant", category: "Animals" },
    { word: "Giraffe", category: "Animals" },
    { word: "Beach", category: "Places" },
    { word: "Mountain", category: "Places" },
    { word: "Soccer", category: "Sports" },
    { word: "Basketball", category: "Sports" },
    { word: "Computer", category: "Technology" },
    { word: "Smartphone", category: "Technology" },
    { word: "Eiffel Tower", category: "Landmarks" },
    { word: "Statue of Liberty", category: "Landmarks" },
    { word: "Pyramid", category: "Landmarks" },
    { word: "Coffee", category: "Drinks" },
    { word: "Tea", category: "Drinks" },
    { word: "Superman", category: "Characters" },
    { word: "Batman", category: "Characters" },
    { word: "Harry Potter", category: "Characters" },
    { word: "Mickey Mouse", category: "Characters" },
    { word: "Christmas", category: "Holidays" },
    { word: "Halloween", category: "Holidays" },
    { word: "Doctor", category: "Professions" },
    { word: "Teacher", category: "Professions" },
    { word: "Firefighter", category: "Professions" },
    { word: "Astronaut", category: "Professions" },
    { word: "Lion", category: "Animals" },
    { word: "Penguin", category: "Animals" },
    { word: "Kangaroo", category: "Animals" },
    { word: "Train", category: "Transport" },
    { word: "Helicopter", category: "Transport" },
    { word: "Submarine", category: "Transport" },
    { word: "Cinema", category: "Places" },
    { word: "Museum", category: "Places" },
    { word: "Zoo", category: "Places" },
    { word: "Ice Cream", category: "Food" },
    { word: "Burger", category: "Food" },
    { word: "Spaghetti", category: "Food" },
    { word: "Camera", category: "Objects" },
    { word: "Watch", category: "Objects" },
    { word: "Glasses", category: "Objects" },
    { word: "Book", category: "Objects" },
    { word: "Moon", category: "Nature" },
    { word: "Sun", category: "Nature" },
    { word: "Rain", category: "Nature" }
];

export const getRandomWord = () => {
    return WORD_LIST[Math.floor(Math.random() * WORD_LIST.length)];
};
